"""Added test_table

Revision ID: ee9e88c4cabc
Revises: 95c582bceefe
Create Date: 2024-07-18 04:17:47.574171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9e88c4cabc'
down_revision = '95c582bceefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at_test', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at_test', sa.DateTime(), server_default=sa.text('now()'),
              nullable=False, server_onupdate=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###
