"""added a 'create_at' column to CommonDetails model.

Revision ID: f7b32b518b68
Revises: 407f9e95afec
Create Date: 2024-07-18 05:15:46.562060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b32b518b68'
down_revision = '407f9e95afec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('business_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('business_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('slack_user_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_user_ids', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('business_credentials', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('business_client', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ai_assistant', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
